npm i request

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -74,12 +74,6 @@ jobs:
       #   run: |
       #     mv artifacts aqua-dht
       #     tar -zcvf aqua-dht.tar.gz aqua-dht
-
-      - name: Compile Aqua to TypeScript
-        working-directory: ./aqua
-        run: |
-          npm i
-          npm run build
       
       - name: Install bcrypt globally
         run: npm i -g bcrypt
@@ -92,13 +86,19 @@ jobs:
         run: |
           ls -l 
           ls -l node_modules || true
-          npm i bcrypt
+          npm i request
+          npm i bcrypt || (echo "failed, mkdir" ; mkdir '/__w/aqua-dht/aqua-dht/aqua/node_modules/bcrypt/lib')
         working-directory: ./aqua
 
       - name: Install bcrypt locally to ./aqua/target/typescript
         run: npm i bcrypt
         working-directory: ./aqua/target/typescript
 
+      - name: Compile Aqua to TypeScript
+        working-directory: ./aqua
+        run: |
+          npm i
+          npm run build
 
       - name: Compile TypeScript to .js + .d.ts
         working-directory: ./aqua/target/typescript
